USE master
DROP DATABASE dbTcc
go
CREATE DATABASE dbTcc
go
use dbTcc
go
create table Tipo_Usuario(
COD_TIPO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOME_TIPO VARCHAR(60) NOT NULL
)
GO
create table Usuarios(
COD_USUARIO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
LOGIN_USUARIO VARCHAR(60) NOT NULL,
SENHA_USUARIO VARCHAR(60) NOT NULL,
TIPO_USUARIO INT NOT NULL,
FOREIGN KEY (TIPO_USUARIO)
REFERENCES Tipo_Usuario(COD_TIPO)
)
INSERT INTO Tipo_Usuario (NOME_TIPO) VALUES ('ADM')
INSERT INTO Tipo_Usuario (NOME_TIPO) VALUES ('USR')

INSERT INTO Usuarios (LOGIN_USUARIO, SENHA_USUARIO, TIPO_USUARIO)VALUES ('admin','admin',1)
INSERT INTO Usuarios (LOGIN_USUARIO, SENHA_USUARIO, TIPO_USUARIO)VALUES ('user','user',2)
INSERT INTO Usuarios (LOGIN_USUARIO, SENHA_USUARIO, TIPO_USUARIO)VALUES ('operador','operador',2)

GO

create table Clientes(
COD_CLIENTE INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOME_CLIENTE VARCHAR(50) NOT NULL,
TIPO_CLIENTE VARCHAR(20) NOT NULL,
CPF_CNPJ_CLIENTE VARCHAR(20) NOT NULL,
IDENTIDADE_CLIENTE VARCHAR(20),
DATA_NASCIMENTO_CLIENTE varchar(10),
EMAIL_CLIENTE VARCHAR(30),
ENDERECO_CLIENTE VARCHAR(50),
NUMERO_ENDERECO_CLIENTE VARCHAR(10),
COMPLEMENTO_CLIENTE VARCHAR(20),
BAIRRO_CLIENTE VARCHAR(30),
CIDADE_CLIENTE VARCHAR(30),
CEP_CLIENTE VARCHAR (9),
UF_CLIENTE VARCHAR(2),
TELEFONE_CLIENTE VARCHAR(15),
CELULAR1_CLIENTE VARCHAR(16),
CELULAR2_CLIENTE VARCHAR (16),
OBS_CLIENTE VARCHAR(60)
)
INSERT INTO Clientes VALUES ('josé Fabio Magalhães Junior', 'Pessoa Física', '456.123.789-32', '481235558', '29/05/1993', 'fabiomagajr@gmail.com', 'Rua das Palmeiras', '58', 'Casa', 'Jardim Casa Grande', 'São Paulo','18240-000', 'SP', '(15)3255-9897', '(15)99658-9898','(15)96565-2121', 'Ele tem um celular a mais')
INSERT INTO Clientes VALUES ('Ana Claudia Cristina Barroso', 'Pessoa Física', '654.987.321-12', '491235558', '05/10/1999', 'anacaludia@gmail.com', 'Rua das Bananas', '70', 'Fundos', 'Avenida Grécia', 'Sorocaba', '18195-000','SP', '(15)3255-5498', '(15)96565-2121','(15)99658-9898', 'Tem computadores demais')
INSERT INTO Clientes VALUES ('Sérgio Pereira Campos', 'Pessoa Física', '321.654.987-23', '478365559', '24/04/1986', 'sergiocampos@gmail.com', 'Rua 70', 's/n', 'Comércio', 'Residencial Capão', 'Campinas','15984-180', 'SP', '(15)3255-3215', '(15)98754-2154','(15)96565-2121', 'Nada a declarar')
go
create table Servicos(
COD_SERVICO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOME_SERVICO VARCHAR(50)NOT NULL,
DURACAO_SERVICO varchar(5) NOT NULL,
OBS_SERVICO VARCHAR (200),
)
INSERT INTO Servicos (NOME_SERVICO,DURACAO_SERVICO)VALUES('CONSULTA SIMPLES','01:00')
INSERT INTO Servicos (NOME_SERVICO,DURACAO_SERVICO)VALUES('PROCESSO JURÍDICO SIMPLES','00:30')

CREATE TABLE Agendamentos
(
COD_AGENDAMENTO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
COD_CLIENTE INT NOT NULL,
COD_SERVICO INT NOT NULL,
DATA_AGENDAMENTO VARCHAR(10),
HORA_INICIO TIME,
HORA_FIM TIME,
OBS_AGENDAMENTO VARCHAR(60),
FOREIGN KEY (COD_CLIENTE)
REFERENCES Clientes(COD_CLIENTE),
FOREIGN KEY (COD_SERVICO)
REFERENCES Servicos(COD_SERVICO)
)
INSERT INTO Agendamentos VALUES (1, 1, '17/10/2015', '13:00', '14:00', 'TEM DORES DE CABEÇA')
INSERT INTO Agendamentos VALUES (2, 2, '17/10/2015', '14:30', '15:00', 'TEM UM COMPUTADOR')
--SELECT COD_AGENDAMENTO, COD_CLIENTE, COD_SERVICO, DATA_AGENDAMENTO, HORA_INICIO, HORA_FIM, OBS_AGENDAMENTO FROM Agendamentos WHERE (1 IS NULL OR COD_AGENDAMENTO LIKE '%1%')
--select * from Usuarios