USE master
DROP DATABASE dbTcc
go
CREATE DATABASE dbTcc
go
use dbTcc
go
create table Tipo_Usuario(
COD_TIPO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOME_TIPO VARCHAR(60) NOT NULL
)
GO
create table Usuarios(
COD_USUARIO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
LOGIN_USUARIO VARCHAR(60) NOT NULL,
SENHA_USUARIO VARCHAR(60) NOT NULL,
TIPO_USUARIO INT NOT NULL,
FOREIGN KEY (TIPO_USUARIO)
REFERENCES Tipo_Usuario(COD_TIPO)
)
INSERT INTO Tipo_Usuario (NOME_TIPO) VALUES ('ADM')
INSERT INTO Tipo_Usuario (NOME_TIPO) VALUES ('USR')

INSERT INTO Usuarios (LOGIN_USUARIO, SENHA_USUARIO, TIPO_USUARIO)VALUES ('admin','admin',1)
INSERT INTO Usuarios (LOGIN_USUARIO, SENHA_USUARIO, TIPO_USUARIO)VALUES ('user','user',2)
INSERT INTO Usuarios (LOGIN_USUARIO, SENHA_USUARIO, TIPO_USUARIO)VALUES ('operador','operador',2)
--SELECT COD_USUARIO, LOGIN_USUARIO, SENHA_USUARIO, TIPO_USUARIO FROM Usuarios WHERE (LOGIN_USUARIO = 'admin') AND (SENHA_USUARIO = 'admin')
--select * from Usuarios
GO
CREATE TABLE Tipo_Cliente
(
COD_TIPO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOME_TIPO VARCHAR(60) NOT NULL
)
go
INSERT INTO Tipo_Cliente (NOME_TIPO) VALUES ('Pessoa Física')
INSERT INTO Tipo_Cliente (NOME_TIPO) VALUES ('Pessoa Jurídica')
go
create table Clientes(
COD_CLIENTE INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOME_CLIENTE VARCHAR(50) NOT NULL,
TIPO_CLIENTE int NOT NULL,
CPF_CNPJ_CLIENTE VARCHAR(20) NOT NULL,
IDENTIDADE_CLIENTE VARCHAR(20),
DATA_NASCIMENTO_CLIENTE VARCHAR(15),
EMAIL_CLIENTE VARCHAR(30),
ENDERECO_CLIENTE VARCHAR(50),
NUMERO_ENDERECO_CLIENTE VARCHAR(10),
COMPLEMENTO_CLIENTE VARCHAR(20),
BAIRRO_CLIENTE VARCHAR(30),
CIDADE_CLIENTE VARCHAR(30),
UF_CLIENTE VARCHAR(2),
TELEFONE_CLIENTE VARCHAR(15),
CELULAR_CLIENTE VARCHAR(16),
OBS_CLIENTE VARCHAR(60),
FOREIGN KEY (TIPO_CLIENTE)
REFERENCES Tipo_Cliente(COD_TIPO)
)
INSERT INTO Clientes VALUES ('josé Fabio Magalhães Junior', 1, '456.123.789-32', '481235558', '29/05/1993', 'fabiomagajr@gmail.com', 'Rua das Palmeiras', '58', 'Casa', 'Jardim Casa Grande', 'São Paulo', 'SP', '(15)3255-9897', '(15)99658-9898', 'Ele tem um celular a mais')
select * from Clientes
--
--SELECT COD_CLIENTE, NOME_CLIENTE, TIPO_CLIENTE, CPF_CNPJ_CLIENTE, IDENTIDADE_CLIENTE, DATA_NASCIMENTO_CLIENTE, EMAIL_CLIENTE, ENDERECO_CLIENTE, NUMERO_ENDERECO_CLIENTE, COMPLEMENTO_CLIENTE, BAIRRO_CLIENTE, CIDADE_CLIENTE, UF_CLIENTE, TELEFONE_CLIENTE, CELULAR_CLIENTE, OBS_CLIENTE FROM Clientes WHERE ('' IS NULL OR NOME_CLIENTE LIKE '%%')
go
create table Servicos(
COD_SERVICO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOME_SERVICO VARCHAR(50)NOT NULL,
DURACAO_SERVICO TIME(4)NOT NULL,
OBS_SERVICO VARCHAR (200),
)
INSERT INTO Servicos (NOME_SERVICO,DURACAO_SERVICO)VALUES('CONSULTA SIMPLES','01:00')
INSERT INTO Servicos (NOME_SERVICO,DURACAO_SERVICO)VALUES('PROCESSO JURÍDICO SIMPLES','00:30')
SELECT * FROM Servicos